// Generated by CoffeeScript 1.3.3
(function() {

  describe('$.globalMessenger', function() {
    var gm, spies, test_msg;
    gm = null;
    test_msg = 'light it up';
    spies = null;
    beforeEach(function() {
      spies = [];
      return gm = $.globalMessenger();
    });
    afterEach(function() {
      var spy, _i, _len, _results;
      gm = null;
      if (spies) {
        _results = [];
        for (_i = 0, _len = spies.length; _i < _len; _i++) {
          spy = spies[_i];
          if (spy) {
            try {
              _results.push(spy.restore());
            } catch (error) {

            }
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    });
    it('should create a new message on post', function() {
      var msg, newMessageSpy;
      newMessageSpy = sinon.spy(gm, 'newMessage');
      spies.push(newMessageSpy);
      msg = gm.post(test_msg);
      return expect(newMessageSpy.called).toBe(true);
    });
    it('should re-render a message on update', function() {
      var msg, renderSpy;
      msg = gm.post(test_msg);
      renderSpy = sinon.spy(msg, 'render');
      spies.push(renderSpy);
      msg.update({
        message: test_msg
      });
      return expect(renderSpy.called).toBe(true);
    });
    return it('should trigger update event on update', function() {
      var msg, triggerSpy;
      msg = gm.post(test_msg);
      triggerSpy = sinon.spy(msg, 'trigger');
      spies.push(triggerSpy);
      msg.update({
        message: test_msg
      });
      return expect(triggerSpy.called).toBe(true);
    });
  });

}).call(this);
